# 1. What is a Python library? Why do we use Python libraries?

----> Python library is a package of the function. Many function can be contain a library to reuse them.Actualy we use a library
to reduce time and efficiently make the project.

# 2. What is the difference between Numpy array and List?

1] --> The List store hetrogeneous types of data.

      --> The array store homogenious types of data.
    
2] --> List is slower than array.

      --> array is faster than list.
    
3] --> List is implemented in python.

     --> array is implemented in c++ over the numpy

4] --> List memory allocation is a dynamic type.

     --> array memory allocation is a static type.

# 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
# importing a libraries
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [4]:
# shape of the array
arr.shape

(3, 4)

In [5]:
# size of the array
arr.size

12

In [6]:
# dimension of the array
arr.ndim

2

# 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [8]:
arr[0]

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [10]:
arr[2,3]

12

# 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [12]:
arr[arr%2 != 0]

array([ 1,  3,  5,  7,  9, 11])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [26]:
arr = np.random.rand(3,3)

In [27]:
arr

array([[0.98378839, 0.86761755, 0.68417956],
       [0.40675248, 0.20107818, 0.71166303],
       [0.397019  , 0.60011614, 0.1456121 ]])

# 8. Describe the difference between np.random.rand and np.random.randn?

 ---->    The difference between the rand and randn function.

        ---> the np.random.rand() function give the result cobination of negative and positive number 
    and np.random.randn() gives the result in positive and both of these function gives the result in between 0 and 1.
    rand() function result based upon the uniform distribution and randn() fuction result based upon the standard normal distribution.
        

# 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [29]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [31]:
arr1 = np.expand_dims(arr,axis=0)

In [34]:
arr.ndim

2

In [35]:
arr1.ndim

3

# 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [36]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [39]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr.T # Transposing the array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

1]. Index wise multiplication 

2]. Matrix multiplication

3]. Add both the matrices

4]. Subtract matrix B from A

5]. Divide matrix B by A

In [44]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [48]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
# 1. index wise multiplication
A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [54]:
# 2. Matrix Multiplication
A @ B.T # well we transpose B beacause the dimension are not same

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [55]:
# 3. Add both the matrices
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [56]:
# 4. Subtract matrix B from A
A - B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
# 5. Divide matrix B by A
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12.  Which function in Numpy can be used to swap the byte order of an array?

---> In NumPy, the numpy.ndarray.byteswap() method can be used to swap the byte order (endianess) of an array.
This method creates a new array with the same data but a different byte order. 
You can specify the byte order using the byteorder parameter.

# 13.  What is the significance of the np.linalg.inv function?

--> The np.linalg.inv function in numpy is used to compute the inverse of a square matrix

# 14. What does the np.reshape function do, and how is it used?

-->  The np.reshape function in numpy is used to change the shape (dimensions) of an array while maintaining 
the total number of elements. 
It does not alter the data;
it merely changes the view of how the data is organized in the array.

# 15. What is broadcasting in Numpy ?


In [ ]:
--> If the arrays have a different number of dimensions, pad the smaller shape with ones on its left side.
Compare the sizes of the corresponding dimensions. If the sizes are different and not equal to 1, 
then the arrays are incompatible.